import { Sour_Gummy } from "next/font/google";
import type { Metadata } from "next";
import "../app/(Home)/globals.css";
import Navigation from "@/components/Navigation";

// font 적용
const sourGummy = Sour_Gummy({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sourGummy.className}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
